name: plan

on:
  push:
    branches-ignore:
      - master

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_ARTIFACT_BUCKET: ${{ secrets.SAM_ARTIFACT_BUCKET }}
  ROLE_CLOUDFORMATION_DEPLOY: ${{ secrets.ROLE_CLOUDFORMATION_DEPLOY }}

jobs:
  plan:
    runs-on: ubuntu-22.04
    concurrency: terraform
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.ROLE_TERRAFORM_DEPLOY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
      - run: tar cf cloud.tar *
      - uses: actions/upload-artifact@v3
        with:
          name: cloud.tar
          path: cloud.tar
      - name: plan
        working-directory: terraform/environment
        run: |
          terraform init
          terraform plan
